-- -----------------------------------------------------
-- Schema full-stack-webshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-webshop`;

CREATE SCHEMA `full-stack-webshop`;
USE `full-stack-webshop` ;

-- -----------------------------------------------------
-- Table `full-stack-webshop`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-webshop`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-webshop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-webshop`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Books');
INSERT INTO product_category(category_name) VALUES ('Coffee Mugs');
INSERT INTO product_category(category_name) VALUES ('T Shirts');


-- -----------------------------------------------------
-- Books
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1000', 'Crash Course in Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Phyton_1.jpg', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1001', 'Become a Guru in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/JavaScript_The_Good_Parts.jpg', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1002', 'Introduction to C# 2', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!!', 'assets/images/products/books/C_1.jpg', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1003', 'Beginners Guide to Machine Learning 3', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Phyton_ML_1.jpg', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1004', 'Beginners Guide to Machine Learning 2', 'Learn Machine Learning with Phyton. Purchase the book and get started today!', 'assets/images/products/books/Phyton_ML_1.jpg', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1005', 'JavaScript Cookbook', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/JavaScript_The_Good_Parts.jpg', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1006', 'Beginners Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/SQL_1.jpg', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1007', 'Advanced Techniques in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/JavaScript_The_Good_Parts.jpg', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1008', 'Introduction to Spring Boot', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Pro_Spring_6.jpg', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1009', 'Pro Spring 6', 'Learn Spring Boot 6 with easy project. Purchase the book and get started today!', 'assets/images/products/books/Pro_Spring_6.jpg', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1010', 'Beginners Guide to Machine Learning', 'Learn Machine Learning with Phyton. Purchase the book and get started today!', 'assets/images/products/books/Phyton_ML_1.jpg', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1011', 'Advanced Techniques in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Java_3.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1012', 'The Go Proggramming 2', 'Learn The Go Proggramming. Purchase the book and get started today!', 'assets/images/products/books/The Go.jpg', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1013', 'The Expert Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/SQL_2.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1014', 'Introduction to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/SQL_3.jpg', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1015', 'The Expert Guide to JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/JavaScript_The_Good_Parts.jpg', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1016', 'Become a Guru in Java 2', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Java_2.jpg', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1017', 'Mastering Kubernetes', 'Learn Mastering Kubernetes. Purchase the book and get started today!', 'assets/images/products/books/Mastering_Kubernetes.jpg', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1018', 'Introduction to C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/C_2.jpg', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1019', 'Crash Course in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/JavaScript_The_Good_Parts.jpg', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1020', 'Internet of Things a Quick Start Guide', 'Learn Internet of Things a Quick Start Guide. Purchase the book and get started today!', 'assets/images/products/books/IoT.jpg', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1021', 'Become a Guru in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Java_1.jpg', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1022', 'Introduction to Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/Phyton_1.jpg', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1023', 'Advanced Techniques in C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 'assets/images/products/books/C_3.jpg', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('BOOK-TECH-1024', 'The Go Proggramming', 'Learn The Go Proggramming. Purchase the book and get started today!', 'assets/images/products/books/The Go.jpg', 1, 100, 16.99, 1, NOW());

-- -----------------------------------------------------
-- Coffee Mugs
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1000', 'Coffee Mug - 1', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1001', 'Coffee Mug - 2', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1002', 'Coffee Mug - 3', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1003', 'Coffee Mug - 4', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1004', 'Coffee Mug - 5', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1005', 'Coffee Mug - 6', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1006', 'Coffee Mug - 7', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1007', 'Coffee Mug - 8', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1008', 'Coffee Mug - 9', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1009', 'Coffee Mug - 10', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1010', 'Coffee Mug - 11', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1011', 'Coffee Mug - 12', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1012', 'Coffee Mug - 13', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1013', 'Coffee Mug - 14', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1014', 'Coffee Mug - 15', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1015', 'Coffee Mug - 16', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1016', 'Coffee Mug - 17', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1017', 'Coffee Mug - 18', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1018', 'Coffee Mug - 19', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1019', 'Coffee Mug - 20', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1020', 'Coffee Mug - 21', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1021', 'Coffee Mug - 22', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_1.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1022', 'Coffee Mug - 23', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_2.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1023', 'Coffee Mug - 24', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java_coffee_3.jpg', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('COFFEEMUG-1024', 'Coffee Mug - 25', 'Do you love programming? This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 'assets/images/products/coffemugs/Java-coffee_0.jpg', 1, 100, 18.99, 2, NOW());

-- -----------------------------------------------------
-- Mouse Pads
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1000', 'T Shirts - 1', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_0.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1001', 'T Shirts - 2', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_1.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1002', 'T Shirts - 3', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_2.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1003', 'T Shirts - 4', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_3.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1004', 'T Shirts - 5', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_4.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1005', 'T Shirts - 6', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_5.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1006', 'T Shirts - 7', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_6.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1007', 'T Shirts - 8', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_7.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1008', 'T Shirts - 9', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_8.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1009', 'T Shirts - 10', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_9.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1010', 'T Shirts - 11', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_10.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1011', 'T Shirts - 12', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_11.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1012', 'T Shirts - 13', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_0.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1013', 'T Shirts - 14', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_1.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1014', 'T Shirts - 15', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_2.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1015', 'T Shirts - 16', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_3.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1016', 'T Shirts - 17', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_4.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1017', 'T Shirts - 18', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_5.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1018', 'T Shirts - 19', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_6.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1019', 'T Shirts - 20', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_7.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1020', 'T Shirts - 21', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_8.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1021', 'T Shirts - 22', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_9.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1022', 'T Shirts - 23', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_10.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1023', 'T Shirts - 24', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_11.jpg', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('TSHIRTS-1024', 'T Shirts - 25', 'Funny programming T Shirt. Buy it now!', 'assets/images/products/tshirts/tshirt_0.jpg', 1, 100, 17.99, 3, NOW());
